mt_config = {
 'dataset': {'preprocess_params': {'output_dim': 0,},},
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 1.0, 
   'perturblmax': 0.0, 
   'perturbθmax': 0.0}},
  'dataset': {'name': 'KFoldsDataset', 'args': {'N': 30, 
   'k': 5, 
   'perturbrmin': 0.0, 
   'perturbrmax': 1.0, 
   'split': 1/3, 
   'seed': 0}},
  'model': {'name': 'MTEnsemble', 'args': {'k': 5}, 
    'switch_profiles': [], 
    'profiles': [{'iterations': 250, 'lr': 0.001}]},
  'optimizer': {'name': 'TorchMT',
   'args': {'optimizer': 'Adam',
    'optimizer_args': {},
    'pos_lr': 0.001,  
    'cell_lr': 0.001, 
    'optimize_atoms': True,
    'optimize_lattice': False, 
    'save_obj_values': True}, 
   'switch_opt_profiles': [20],
   'opt_profiles': [{'starts': 128, 'iters_per_start': 100,}, 
    {'starts': 1024, 'iters_per_start': 1000,}],
   'switch_acq_profiles': [20],
   'acq_profiles': [{'name': 'MAEUncertainty', 'args': {'λ': 0.1}}, 
    {'name': 'MAE', 'args': {}}],
   }}}

torchmd_config = {
 'trainer': 'property',
 'task': {'identifier': 'my_train_job',
  'parallel': False,
  'save_dir': None,
  'continue_job': False,
  'load_training_state': False,
  'checkpoint_path': None,
  'write_output': [],
  'use_amp': True,
  'run_mode': 'train',
  'model_save_frequency': -1},
 'model': {
   'name': 'torchmd_etEarly',
   'hidden_channels': 64,
   'num_filters': 128,
   'num_layers': 6,
   'num_rbf': 50,
   'rbf_type': 'expnorm',
   'trainable_rbf': True,
   'activation': 'silu',
   'attn_activation': 'silu',
   'num_heads': 8,
   'distance_influence': 'both',
   'neighbor_embedding': True,
   'cutoff_lower': 0.0,
   'cutoff_upper': 8.0,
   'max_z': 100,
   'max_num_neighbors': 32,
   'aggr': 'add',
   'num_post_layers': 2,
   'post_hidden_channels': 128,
   'pool': 'global_mean_pool',
   'otf_edge_index': False,
   'otf_edge_attr': False,
   'otf_node_attr': False,
   'model_ensemble': 1,
   'gradient': False,
 },
 'optim': {'max_epochs': 500,
  'max_checkpoint_epochs': 0,
  'lr': 0.001,
  'loss': {'loss_type': 'TorchLossWrapper',
   'loss_args': {'loss_fn': 'l1_loss'}},
  'clip_grad_norm': 10,
  'batch_size': 1000,
  'optimizer': {'optimizer_type': 'AdamW', 'optimizer_args': {}},
  'scheduler': {'scheduler_type': 'ReduceLROnPlateau',
   'scheduler_args': {'mode': 'min',
    'factor': 0.8,
    'patience': 10,
    'min_lr': 1e-05,
    'threshold': 0.0002}},
  'verbosity': 1,
  'batch_tqdm': False},
 'dataset': {'name': 'test_data',
  'processed': False,
  'dataset_device': 'cpu',
  'target_path': None,
  'pt_path': 'data/',
  'prediction_level': 'graph',
  'transforms': [{'name': 'GetY', 'args': {'index': -1}, 'otf': True}],
  'data_format': 'json',
  'additional_attributes': None,
  'verbose': True,
  'preprocess_params': {'edge_calc_method': 'ocp',
   'preprocess_edges': True,
   'preprocess_edge_features': True,
   'preprocess_node_features': True,
   'cutoff_radius': 8.0,
   'n_neighbors': 250,
   'num_offsets': 2,
   'node_dim': 100,
   'edge_dim': 50,
   'prediction_level': 'graph',
   'self_loop': True,
   'node_representation': 'onehot',
   'all_neighbors': True}},
 'submit': None,
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 1.0, 
   'perturblmax': 0.0, 
   'perturbθmax': 0.0}},
  'dataset': {'name': 'KFoldsDataset', 'args': {'N': 30, 
   'k': 5, 
   'perturbrmin': 0.0, 
   'perturbrmax': 1.0, 
   'split': 1/3, 
   'seed': 0}},
  'model': {'name': 'GNNEnsemble', 'args': {'k': 5}, 
    'switch_profiles': [], 
    'profiles': [{'iterations': 500, 'lr': 0.001}]},
  'optimizer': {'name': 'Torch',
   'args': {'optimizer': 'Adam',
    'optimizer_args': {},
    'pos_lr': 0.001,  
    'cell_lr': 0.001, 
    'optimize_atoms': True,
    'optimize_lattice': False, 
    'save_obj_values': True}, 
   'switch_opt_profiles': [20],
   'opt_profiles': [{'starts': 128, 'iters_per_start': 100,}, 
    {'starts': 1024, 'iters_per_start': 1000,}],
   'switch_acq_profiles': [20],
   'acq_profiles': [{'name': 'MAEUncertainty', 'args': {'λ': 0.1}}, 
    {'name': 'MAE', 'args': {}}],
   }}}

groundtruth_config = {
 'trainer': 'property',
 'task': {'identifier': 'my_train_job',
  'parallel': False,
  'save_dir': None,
  'continue_job': False,
  'load_training_state': False,
  'checkpoint_path': None,
  'write_output': [],
  'use_amp': True,
  'run_mode': 'train',
  'model_save_frequency': -1},
 'model': {
   'name': 'torchmd_etEarly',
   'hidden_channels': 64,
   'num_filters': 128,
   'num_layers': 6,
   'num_rbf': 50,
   'rbf_type': 'expnorm',
   'trainable_rbf': True,
   'activation': 'silu',
   'attn_activation': 'silu',
   'num_heads': 8,
   'distance_influence': 'both',
   'neighbor_embedding': True,
   'cutoff_lower': 0.0,
   'cutoff_upper': 8.0,
   'max_z': 100,
   'max_num_neighbors': 32,
   'aggr': 'add',
   'num_post_layers': 2,
   'post_hidden_channels': 128,
   'pool': 'global_mean_pool',
   'otf_edge_index': False,
   'otf_edge_attr': False,
   'otf_node_attr': False,
   'model_ensemble': 1,
   'gradient': False,
 },
 'optim': {'max_epochs': 500,
  'max_checkpoint_epochs': 0,
  'lr': 0.001,
  'loss': {'loss_type': 'TorchLossWrapper',
   'loss_args': {'loss_fn': 'l1_loss'}},
  'clip_grad_norm': 10,
  'batch_size': 1000,
  'optimizer': {'optimizer_type': 'AdamW', 'optimizer_args': {}},
  'scheduler': {'scheduler_type': 'ReduceLROnPlateau',
   'scheduler_args': {'mode': 'min',
    'factor': 0.8,
    'patience': 10,
    'min_lr': 1e-05,
    'threshold': 0.0002}},
  'verbosity': 1,
  'batch_tqdm': False},
 'dataset': {'name': 'test_data',
  'processed': False,
  'dataset_device': 'cpu',
  'target_path': None,
  'pt_path': 'data/',
  'prediction_level': 'graph',
  'transforms': [{'name': 'GetY', 'args': {'index': -1}, 'otf': True}],
  'data_format': 'json',
  'additional_attributes': None,
  'verbose': True,
  'preprocess_params': {'edge_calc_method': 'ocp',
   'preprocess_edges': True,
   'preprocess_edge_features': True,
   'preprocess_node_features': True,
   'cutoff_radius': 13.0,
   'n_neighbors': 10000,
   'num_offsets': 4,
   'node_dim': 100,
   'edge_dim': 50,
   'prediction_level': 'graph',
   'self_loop': True,
   'node_representation': 'onehot',
   'all_neighbors': True}},
 'submit': None,
 'aso_params': {'max_forward_calls': 31,
  'sampler': {'name': 'Perturbation', 
    'args': {'perturblσ': 0.1, 'perturbrmin': 0.1, 'perturbrmax': 1.0}},
  'dataset': {'name': 'KFoldsDataset', 'args': {'N': 30, 
   'k': 5, 
   'perturbrmin': 0.0, 
   'perturbrmax': 1.0, 
   'split': 1/3, 
   'device': 'cuda', 
   'seed': 0}},
  'model': {'name': 'GroundTruth', 'args': {}, 
    'switch_profiles': [], 
    'profiles': [{}]},
  'optimizer': {'name': 'TorchBH',
   'args': {'optimizer': 'Adam',
    'optimizer_args': {},
    'hops': 10000,
    'iters_per_hops': 100,
    'pos_lr': 0.01,
    'cell_lr': 0.01,
    'optimize_atoms': True,
    'optimize_lattice': True,
    'constraint_scale': 1.0,
    'σ': 0.02, 
    'save_obj_values': True,
    'hop_sampler': 'SingleAtomPerturbation', 
    'hop_sampler_args': {'perturbrmin': 0.2, 'perturbrmax': 0.2, 
      'perturblmax': 0, 'perturbθmax': 0, 'lattice_prob': 0}}, 
   'switch_profiles': [],
   'profiles': [{'name': 'MSE', 'args': {}}],
   }}}

torchmd_rmc_config = {
 'trainer': 'property',
 'task': {'identifier': 'my_train_job',
  'parallel': False,
  'save_dir': None,
  'continue_job': False,
  'load_training_state': False,
  'checkpoint_path': None,
  'write_output': [],
  'use_amp': True,
  'run_mode': 'train',
  'model_save_frequency': -1},
 'model': {
   'name': 'torchmd_etEarly',
   'hidden_channels': 64,
   'num_filters': 128,
   'num_layers': 6,
   'num_rbf': 50,
   'rbf_type': 'expnorm',
   'trainable_rbf': True,
   'activation': 'silu',
   'attn_activation': 'silu',
   'num_heads': 8,
   'distance_influence': 'both',
   'neighbor_embedding': True,
   'cutoff_lower': 0.0,
   'cutoff_upper': 8.0,
   'max_z': 100,
   'max_num_neighbors': 32,
   'aggr': 'add',
   'num_post_layers': 2,
   'post_hidden_channels': 128,
   'pool': 'global_mean_pool',
   'otf_edge_index': False,
   'otf_edge_attr': False,
   'otf_node_attr': False,
   'model_ensemble': 1,
   'gradient': False,
 },
 'optim': {'max_epochs': 500,
  'max_checkpoint_epochs': 0,
  'lr': 0.001,
  'loss': {'loss_type': 'TorchLossWrapper',
   'loss_args': {'loss_fn': 'l1_loss'}},
  'clip_grad_norm': 10,
  'batch_size': 1000,
  'optimizer': {'optimizer_type': 'AdamW', 'optimizer_args': {}},
  'scheduler': {'scheduler_type': 'ReduceLROnPlateau',
   'scheduler_args': {'mode': 'min',
    'factor': 0.8,
    'patience': 10,
    'min_lr': 1e-05,
    'threshold': 0.0002}},
  'verbosity': 1,
  'batch_tqdm': False},
 'dataset': {'name': 'test_data',
  'processed': False,
  'dataset_device': 'cpu',
  'target_path': None,
  'pt_path': 'data/',
  'prediction_level': 'graph',
  'transforms': [{'name': 'GetY', 'args': {'index': -1}, 'otf': True}],
  'data_format': 'json',
  'additional_attributes': None,
  'verbose': True,
  'preprocess_params': {'edge_calc_method': 'ocp',
   'preprocess_edges': True,
   'preprocess_edge_features': True,
   'preprocess_node_features': True,
   'cutoff_radius': 8.0,
   'n_neighbors': 250,
   'num_offsets': 2,
   'node_dim': 100,
   'edge_dim': 50,
   'prediction_level': 'graph',
   'self_loop': True,
   'node_representation': 'onehot',
   'all_neighbors': True}},
 'submit': None,
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 1.0, 
   'perturblmax': 0.0, 
   'perturbθmax': 0.0}},
  'dataset': {'name': 'KFoldsDataset', 'args': {'N': 30, 
   'k': 5, 
   'perturbrmin': 0.0, 
   'perturbrmax': 1.0, 
   'split': 1/3, 
   'device': 'cuda', 
   'seed': 0}},
  'model': {'name': 'GNNEnsemble', 'args': {'k': 5}, 
    'switch_profiles': [], 
    'profiles': [{'iterations': 500, 'lr': 0.001}]},
  'optimizer': {'name': 'RMC',
   'args': {'starts': 10, 
    'iters_per_start': 1000, 
    'save_obj_values': True}, 
   'switch_profiles': [20],
   'profiles': [{'name': 'MAEUncertainty', 'args': {'λ': 0.1}}, 
    {'name': 'MAE', 'args': {}}],
   }}}

rmc_config = {
 'dataset': {'preprocess_params': {'prediction_level': 'graph'}},
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 0.1, 
   'perturblmax': 0.0, 
   'perturbθmax': 0.0}},
  'dataset': {'name': 'RMCList', 'args': {'seed': 0, 'σ': 0.0025}},
  'model': {'name': 'NoModel', 'args': {}, 
   'switch_profiles': [], 'profiles': [{}]},
  'optimizer': {'name': 'RMCStep',
   'args': {}, 
   'switch_profiles': [],
   'profiles': [{'name': 'MAE', 'args': {}}],
   }}}
   
bogp_config = {
'dataset': {'preprocess_params': {'prediction_level': 'graph'}},
'aso_params': {'max_forward_calls': 100,
'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
  'perturbrmax': 0.1, 
  'perturblmax': 0.0, 
  'perturbθmax': 0.0}},
'dataset': {'name': 'BOSet', 'args': {'seed': 0, 'N': 30}},
'model': {'name': 'GaussianProcess', 'args': {}, 
  'switch_profiles': [], 'profiles': [{}]},
'optimizer': {'name': 'BOTorch',
  'args': {}, 
  'switch_profiles': [],
  'profiles': [{'name': 'MAE', 'args': {}}],
  }}}

random_config = {
 'dataset': {'preprocess_params': {'prediction_level': 'graph'}},
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 1.0, 
   'perturblmax': 0.0, 
   'perturbθmax': 0.0}},
  'dataset': {'name': 'SimpleDataset', 'args': {'seed': 0}},
  'model': {'name': 'NoModel', 'args': {}, 
   'switch_profiles': [], 'profiles': [{}]},
  'optimizer': {'name': 'Random',
   'args': {}, 
   'switch_profiles': [],
   'profiles': [{'name': 'MAE', 'args': {}}],
   }}}
   
pso_config = {
 'trainer': 'property',
 'task': {'identifier': 'my_train_job',
  'parallel': False,
  'save_dir': None,
  'continue_job': False,
  'load_training_state': False,
  'checkpoint_path': None,
  'write_output': [],
  'use_amp': True,
  'run_mode': 'train',
  'model_save_frequency': -1},
 'model': {
   'name': 'torchmd_etEarly',
   'hidden_channels': 64,
   'num_filters': 128,
   'num_layers': 6,
   'num_rbf': 50,
   'rbf_type': 'expnorm',
   'trainable_rbf': True,
   'activation': 'silu',
   'attn_activation': 'silu',
   'num_heads': 8,
   'distance_influence': 'both',
   'neighbor_embedding': True,
   'cutoff_lower': 0.0,
   'cutoff_upper': 8.0,
   'max_z': 100,
   'max_num_neighbors': 32,
   'aggr': 'add',
   'num_post_layers': 2,
   'post_hidden_channels': 128,
   'pool': 'global_mean_pool',
   'otf_edge_index': False,
   'otf_edge_attr': False,
   'otf_node_attr': False,
   'model_ensemble': 1,
   'gradient': False,
 },
 'optim': {'max_epochs': 500,
  'max_checkpoint_epochs': 0,
  'lr': 0.001,
  'loss': {'loss_type': 'TorchLossWrapper',
   'loss_args': {'loss_fn': 'l1_loss'}},
  'clip_grad_norm': 10,
  'batch_size': 1000,
  'optimizer': {'optimizer_type': 'AdamW', 'optimizer_args': {}},
  'scheduler': {'scheduler_type': 'ReduceLROnPlateau',
   'scheduler_args': {'mode': 'min',
    'factor': 0.8,
    'patience': 10,
    'min_lr': 1e-05,
    'threshold': 0.0002}},
  'verbosity': 1,
  'batch_tqdm': False},
 'dataset': {'name': 'test_data',  # Single merged dataset key
  'processed': False,
  'dataset_device': 'cpu',
  'target_path': None,
  'pt_path': 'data/',
  'prediction_level': 'graph',
  'transforms': [{'name': 'GetY', 'args': {'index': -1}, 'otf': True}],
  'data_format': 'json',
  'additional_attributes': None,
  'verbose': True,
  'preprocess_params': {'edge_calc_method': 'ocp',
   'preprocess_edges': True,
   'preprocess_edge_features': True,
   'preprocess_node_features': True,
   'cutoff_radius': 8.0,
   'n_neighbors': 250,
   'num_offsets': 2,
   'node_dim': 100,
   'edge_dim': 50,
   'prediction_level': 'graph',
   'self_loop': True,
   'node_representation': 'onehot',
   'all_neighbors': True}},
 'submit': None,
 'aso_params': {'max_forward_calls': 100,
  'sampler': {'name': 'Perturbation', 'args': {'perturbrmin': 0.1, 
   'perturbrmax': 1.0}},
  'dataset': {'name': 'KFoldsDataset', 'args': {'N': 30, 
   'k': 5, 
   'perturbrmin': 0.0, 
   'perturbrmax': 1.0, 
   'split': 1/3, 
   'device': 'cuda', 
   'seed': 0}},
  'model': {'name': 'GNNEnsemble', 'args': {'k': 5}, 
    'switch_profiles': [], 
    'profiles': [{'iterations': 500, 'lr': 0.001}]},
  'optimizer': {'name': 'PSO2',
   'args': {
    'particles': 10,
    'iters': 50,
    'local_steps': 0,
    'c1': 1.2,
    'c2': 1.2,
    'w': 0.5,
    'optimize_atoms': True,
    'optimize_lattice': True,
    'constraint_scale': 1.0,
    'save_obj_values': True,
    'use_torchsim': False,
   }, 
   'switch_profiles': [20],
   'profiles': [{'name': 'MAEUncertainty', 'args': {'λ': 0.1}}, 
    {'name': 'MAE', 'args': {}}],
    'switch_acq_profiles': [20],
   'acq_profiles': [{'name': 'MAEUncertainty', 'args': {'λ': 0.1}}, 
    {'name': 'MAE', 'args': {}}],
   }}}